# -*- coding: utf-8 -*-
"""PECIER_modulo3_parte3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2Zk8ICvVWnNPJyGmNnRWymSYvFmB2CR

# Día 3 Parte 3: Importación de Módulos y Bibliotecas en Python

## Ejemplos

**Ejemplo 3.10: Usar un módulo de la biblioteca estándar**

En este primer ejemplo importamos la biblioteca math donde están programadas casi todas las funciones matemáticas de mayor relevancia.
"""

import math

print(f"Raíz cuadrada de 16: {math.sqrt(16)}")
print(f"Valor de pi: {math.pi}")

"""Usualmente cada biblioteca tiene su página de documentación. Ver: https://docs.python.org/3/library/math.html

**Ventaja**: Las operaciones son mucho más rápidas que usar listas tradicionales.

**Ejemplo 3.11: Consumo eléctrico por hora**
"""

import matplotlib.pyplot as plt

horas = range(24)
consumo = [50 + 10*h + 5*(h % 3) for h in horas]  # simulación simple

plt.figure(figsize=(10, 5))
plt.plot(horas, consumo, 'r-o', label='Consumo (kW)')
plt.title("Perfil de Carga Diario")
plt.xlabel("Hora del día")
plt.ylabel("Potencia (kW)")
plt.grid(True)
plt.legend()
plt.show()

"""
**Ejemplo 3.12:** Gráfica de barras


"""

sectores = ['Administración', 'Producción', 'Mantenimiento']
consumos = [1200, 4500, 2100]

plt.figure(figsize=(8, 5))
plt.bar(sectores, consumos, color=['blue', 'green', 'orange'])
plt.title("Consumo por Sector")
plt.ylabel("Consumo mensual (kWh)")
plt.grid(axis='y')
plt.show()

"""**Ejemplo 3.13: Ampliación del anterior**"""

import matplotlib.pyplot as plt
import numpy as np

# Paso 1: Ampliar el rango de horas
horas = range(24)

# Paso 2: Crear una lista de consumo de 24 valores (patrón simple repetido)
consumo = [100 + 10*(h % 6) for h in horas]

# Paso 3: Calcular el promedio
promedio = np.mean(consumo)

# Paso 4: Graficar
plt.figure(figsize=(10, 5))
plt.plot(horas, consumo, 'g-s', label='Consumo horario (kW)')  # línea verde con cuadrados
plt.axhline(promedio, color='red', linestyle='--', label=f'Promedio = {promedio:.1f} kW')  # línea de promedio

plt.title("Perfil de Consumo Diario Modificado")
plt.xlabel("Hora del día")
plt.ylabel("Potencia (kW)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""Conviene revisar la documentación: https://matplotlib.org/cheatsheets/
¡Su propia página web!

## Ejercicios

**Ejercicio 3.10**

Crea un módulo llamado `transformadores.py` con una función que calcule la relación de transformación de un transformador:
"""

def relacion_transformacion(V_primario, V_secundario):
    """Relación n = Vp / Vs"""
    return V_primario / V_secundario

"""Luego crea un archivo `main.py` que use esa función.

**Ejercicio 3.11 (Visualización)**
Analizar el siguiente código y realizar las correcciones necesarias para que se ejecute correctamente
"""

import matplotlib.pyplot as plot
import numpy as np

# Generamos datos sintéticos: 7 días x 24 horas = 168 puntos
horas_por_dia = 24
dias = 7
total_horas = horas_por_dia * dias

# Simulación de perfil de carga:
# Día: más consumo en horas pico (8-18 h), Noche: menos consumo
demanda = []
for dia in range(dias):
    for hora in range(horas_por_dia):
        if 8 <= hora <= 18:
            base = 150  # consumo base en horas laborales
        else:
            base = 80   # consumo reducido por la noche
        # Aumentamos carga los días laborales (lunes a viernes)
        if dia < 5:
            ruido = np.random.normal(0, 10)
        else:
            ruido = np.random.normal(-10, 5)  # menor carga fines de semana
        demanda.append(base + ruido)

# Crear arreglo de tiempo (0 a 167 horas)
tiempo = np.arange(total_horas)

# Graficar
plt.figure(figsize=(14, 6))
plt.plot(tiempo, demanda, label='Demanda (kW)', color='blue')
plt.title('Demanda Eléctrica de una Planta durante una Semana')
plt.xlabel('Hora')
plt.ylabel('Potencia (kW)')
plt.grid(True)
plt.axvline(24, color='gray', linestyle='--')
plt.axvline(48, color='gray', linestyle='--')
plt.axvline(72, color='gray', linestyle='--')
plt.axvline(96, color='gray', linestyle='--')
plt.axvline(120, color='gray', linestyle='--')
plt.axvline(144, color='gray', linestyle='--')
plt.legend()
plt.tight_layout()
plt.show()

# Espacio para resolver el ejercicio
# Corregir import plot con import plt

"""**Ejercicio 3.12 (Errores comunes)**
Corrige los errores de este código:
"""

from math import pow, sqrt

def energia(V, t):
    return pow(V, 2) / t

print(sqrt(energia(220)))  # Error

# Espacio para resolver el ejercicio
# Nota: Observar la cantidad de argumentos de la función