# -*- coding: utf-8 -*-
"""PECIER_modulo3_parte1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goHIJlblBqLpEi5TnC3hwBPDCYddZw1D

# Día 3 Parte 1: Definición y Uso de Funciones en Python

## Ejemplos

**Ejemplo 3.1:** Función básica, sin parámetros
"""

def mostrar_menu():

    print("\n1. Calcular potencia")
    print("2. Analizar circuito")
    print("3. Salir")

mostrar_menu()  # Llamada a la función

"""**Ejemplo 3.2: Función que muestre las normas de seguridad eléctrica.**"""

def mostrar_normas_seguridad():
    print("\nNormas de Seguridad Eléctrica:")
    print("1. Siempre apaga la energía antes de realizar reparaciones.")
    print("2. Usa equipo de protección personal (guantes, gafas, etc.).")
    print("3. Asegúrate de que el área esté seca antes de trabajar con electricidad.")
    print("4. Verifica siempre las conexiones antes de poner en marcha los equipos.")
    print("5. No sobrecargues los circuitos eléctricos.")

# Llamada a la función
mostrar_normas_seguridad()

"""**Ejemplo 3.3:** Función con parámetros"""

def calcular_potencia(voltaje, corriente):
    """Calcula P = V * I"""
    return voltaje * corriente * factor_potencia

# Uso con parámetros posicionales
potencia = calcular_potencia(220, 10)
print(f"Potencia: {potencia}W")

"""**Ejemplo 3.3.1**"""

# Uso con parámetros nombrados
print(f"Potencia con factor: {calcular_potencia(corriente=15, voltaje=110)}W")

"""**Ejemplo 3.4:** Función que retorma múltiples valores"""

### Código de ejemplo:

def analizar_circuito(V, I):
    P = V * I
    R = V / I if I != 0 else float('inf')  # Evita división por cero
    return P, R  # Retorna una tupla con dos valores

# Llamada a la función
potencia, resistencia = analizar_circuito(220, 5)

# Mostrar resultados
print(f"P: {potencia}W, R: {resistencia}Ω")

"""
**Ejemplo 3.5: Ámbito de Variables**  

En programación, el **ámbito** (o *scope*) se refiere al lugar del programa donde una variable es válida y accesible. En Python, existen principalmente dos tipos de ámbito:

- **Variables globales**: Son las que se definen fuera de cualquier función y están disponibles en todo el programa.
- **Variables locales**: Son las que se definen dentro de una función y solo existen mientras esa función se está ejecutando.
"""

### Código de ejemplo:


energia_total = 0  # Variable global

def calcular_consumo(horas, potencia):
    consumo = horas * potencia  # Variable local
    global energia_total
    energia_total += consumo
    return consumo

print(calcular_consumo(8, 1500))  # 12000
print(f"Energía total: {energia_total}Wh")

# Dentro de la función `calcular_consumo`:


def calcular_consumo(horas, potencia):

"""- Se definen dos parámetros: `horas` y `potencia`, que se usarán dentro de la función.

"""

consumo = horas * potencia

"""
- Esta es una **variable local**, que solo existe **dentro de la función**.
- Calcula el consumo de energía en Wh (vatios por hora).

"""

global energia_total

"""- Esto indica que dentro de la función vamos a modificar la variable global `energia_total`.
- Sin esta línea, Python asumiría que estamos creando una nueva variable local con ese nombre, y no modificaría la global.
"""

energia_total += consumo

"""- Aquí sí modificamos la variable global, **acumulando el consumo calculado**."""

# Uso de la función:

print(f"Energía total: {energia_total}Wh")

"""- Al imprimir, podemos ver cómo la variable global `energia_total` refleja el valor acumulado luego de ejecutar la función.

**Ejemplo 3.6:**
"""

#Ejemplo práctico: Configuración de transformadores

def configurar_transformador(nombre, voltaje=220, frecuencia=60):
    print(f"\nTransformador {nombre}:")
    print(f"Voltaje: {voltaje}V")
    print(f"Frecuencia: {frecuencia}Hz")

# Uso con valores por defecto
configurar_transformador("T1")

# Uso personalizado
configurar_transformador("T2", voltaje=440, frecuencia=50)

"""#### **¿Qué está pasando?**

1. La función `configurar_transformador` tiene dos parámetros con valores por defecto:
   - `voltaje=220`
   - `frecuencia=60`

2. Cuando llamamos `configurar_transformador("T1")`, no damos valores para los otros dos parámetros, por lo tanto se usan los predeterminados:
   → Voltaje = 220V, Frecuencia = 60Hz

3. En la segunda llamada, sí pasamos valores específicos:
   → Voltaje = 440V, Frecuencia = 50Hz

---

#### **Ventaja:**
- Simplifica el uso de funciones cuando la mayoría de los valores son comunes.

**Ejemplo 3.7: Avanzado**
"""

## Ejemplo: Diagnóstico de sensores
def diagnosticar(*sensores, **umbrales):
    print("\nSensores analizados:", sensores)
    print("Umbrales aplicados:", umbrales)

diagnosticar("Temp1", "Temp2", "Corriente",
             temp_max=85, corriente_max=20)

"""**¿Qué hace este código?**

1. `*sensores` agrupa todos los argumentos posicionales en una **tupla**:
   → `("Temp1", "Temp2", "Corriente")`

2. `**umbrales` agrupa los argumentos nombrados en un **diccionario**:
   → `{"temp_max": 85, "corriente_max": 20}`

3. La función los imprime para mostrar qué sensores se van a diagnosticar y qué límites se aplicarán.

---
**¿Para qué sirve esto?**
- Muy útil para funciones generales que deben adaptarse a diferentes equipos, configuraciones o tipos de sensores.
- Se adapta a entradas cambiantes sin necesidad de reescribir la función.

## Ejercicios

**Ejercicio 3.1: Modifica la función del Ejemplo 3.1 para que incluya un parámetro `factor_potencia` (valor por defecto=1).**
Este parámetro se multiplicará por la potencia calculada.
"""

# Espacio para resolver el ejercicio

"""**Ejercicio 3.2: Modifica la función `analizar_circuito` del Ejemplo 3.4 para que también retorne la energía consumida si se conoce el tiempo en horas (`t_horas`).**

Si no se proporciona tiempo, asume que es 1 hora.

> Recuerde que:
> \[
> \text{Energía} = \text{Potencia} x \text{Tiempo}
> \]

"""

# Sugerencia:

def analizar_circuito(V, I, t_horas=1):
    P = V * I
    R = V / I if I != 0 else float('inf')
    energia = P * t_horas
    return P, R, energia

# Espacio para resolver el ejercicio

"""**Ejercicio 3.3:** Crea una función que use una variable local para representar una operación, y una variable global que rastree cuántas veces se ha llamado esa función."""

# Espacio para resolver el ejercicio

# Ejemplo sugerido:

contador_llamadas = 0  # Variable global

def registrar_uso():
    global contador_llamadas
    contador_llamadas += 1  # Aumenta cada vez que se llama
    mensaje = f"Función llamada {contador_llamadas} veces"
    return mensaje

# Uso
print(registrar_uso())
print(registrar_uso())
print(f"Total de llamadas: {contador_llamadas}")

"""---

**Ejercicio 3.4:** Extender la función analizar_circuito para que también calcule la Energía Eléctrica (E) consumida durante un tiempo determinado..

Para esto:
- Modificar la función analizar_circuito para que acepte un tercer argumento, t (tiempo en horas).

- Calcular la Energía (E) usando la fórmula E=P⋅t
"""

# Espacio para resolver el ejercicio

"""## Proyecto:"""

## **5. Proyecto: Sistema de Gestión de Circuitos**

En este proyecto, se pretende construir un sistema básico de gestión y análisis de circuitos eléctricos utilizando funciones, estructuras de datos y lógica condicional. El propósito es simular cómo se podría estructurar un sistema que:

- Registre circuitos eléctricos con diferentes componentes
- Analice automáticamente si un circuito cumple ciertas condiciones mínimas de seguridad y diseño
- Emita alertas si hay configuraciones problemáticas

Este proyecto integra los conocimientos que ya has trabajado: funciones, listas, condicionales, diccionarios y retornos múltiples.

"""### **Instrucciones:**

1. Implementar la función `crear_circuito` que registre un circuito con un nombre, una lista de componentes, y marque su estado como "activo".
2. Usa la función `analizar_circuito` para comprobar si el circuito:
   - Tiene más de 10 componentes → Genera alerta.
   - No contiene un "Transformador" → Genera alerta.
3. Prueba tu sistema con diferentes circuitos y observa los mensajes.





"""

# Función para crear un circuito
def crear_circuito(nombre, componentes):
    """Registra un nuevo circuito eléctrico"""
    return {
        "nombre": nombre,
        "componentes": componentes,
        "estado": "activo"
    }

# Función para analizar un circuito y detectar condiciones críticas
def analizar_circuito(circuito):
    """Evalúa condiciones de operación del circuito"""
    alertas = []

    # Condición 1: Demasiados componentes
    if len(circuito["componentes"]) > 10:
        alertas.append("Demasiados componentes")

    # Condición 2: Falta un transformador
    if "Transformador" not in circuito["componentes"]:
        alertas.append("Falta transformador")

    # Resultado del análisis
    return alertas if alertas else "OK"

# -----------------------------
# Uso del sistema

# Circuito con configuración válida
circuito_1 = crear_circuito("Principal",
                            ["Transformador", "Interruptor", "Fusible"])
print("Análisis del circuito 'Principal':")
print(analizar_circuito(circuito_1))

# Circuito con problemas (sin transformador y muchos componentes)
circuito_2 = crear_circuito("Secundario",
                            ["Fusible", "Interruptor", "Medidor", "Contacto",
                             "Cableado", "Disyuntor", "Conector", "Interruptor",
                             "Medidor", "Interruptor", "Interruptor"])
print("\nAnálisis del circuito 'Secundario':")
print(analizar_circuito(circuito_2))

"""## **Ejercicios Adicionales**


### **1. Validación de Datos**

#### Propósito:
Aprender a crear funciones que **verifican si los valores eléctricos están dentro de un rango seguro**.

#### Actividad:
Verificar el funcionamiento de `validar_medicion` recibe un valor (por ejemplo, voltaje), un mínimo y un máximo.

"""

def validar_medicion(valor, minimo, maximo):
    """Retorna True si el valor está en rango"""
    return minimo <= valor <= maximo

# Pruebas
if not validar_medicion(250, 200, 240):
    print("¡Voltaje peligroso detectado!")

"""### **2. Cálculo de Costos**

#### Propósito:
Aplicar funciones con **parámetros por defecto** para simular un cálculo de facturación eléctrica.

#### Actividad:

Analizar la función `calcular_costo`, que recibe el consumo eléctrico en kWh y devuelve el total considerando una tarifa base y un impuesto adicional.




"""

```python
def calcular_costo(consumo_kWh, tarifa=0.15, impuestos=0.18):
    subtotal = consumo_kWh * tarifa
    total = subtotal * (1 + impuestos)
    return round(total, 2)

print(f"Costo total: ${calcular_costo(350, tarifa=0.12)}")
```

"""**Reto adicional:**

- Mostrar el **desglose completo** de costos: consumo, subtotal, impuestos y total.
- Agrega validación: si el consumo es negativo o cero, muestra un mensaje de error.



"""

