# -*- coding: utf-8 -*-
"""PECIER_modulo3_parte2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTsFbY7sEwgUDp8yE2FWeejpxAhLVkGG

# Día 3 Parte 2: Parámetros y Valores de Retorno en Python

## Ejemplos

**Ejemplo 3.6:** Cantidad indefinida de parámetros (Avanzado)
"""

def promedio_consumo(*consumos):
    if not consumos:
        return 0
    return sum(consumos) / len(consumos)

print(promedio_consumo(120, 150, 135, 140))  # 136.25

"""**Ejemplo 3.7:**"""

def crear_reporte(**datos):
    print("\n--- REPORTE ---")
    for clave, valor in datos.items():
        print(f"{clave.title().replace('_', ' ')}: {valor}")

crear_reporte(
    equipo="T-125",
    voltaje_operacion=220,
    ubicacion="Planta Sur",
    estado="Operativo"
)

"""**Ejemplo 3.8:**"""

def analizar_circuito(voltaje, corriente):
    potencia = voltaje * corriente
    resistencia = voltaje / corriente if corriente else float('inf')
    estado = "OK" if potencia < 5000 else "SOBRECARGA"
    return potencia, resistencia, estado

p, r, e = analizar_circuito(220, 15)
print(f"P: {p}W, R: {r:.2f}Ohm, Estado: {e}")

"""**Importante:** Observe que en el llamado a la función se establecen los nombres de las variables de retorno.

**Ejemplo 3.9:**
"""

def diagnostico_motor(voltaje, corriente, rpm):
    potencia_entrada = voltaje * corriente
    potencia_mecanica = rpm * 0.1047 * corriente
    eficiencia = (potencia_mecanica / potencia_entrada) if potencia_entrada else 0
    estado = "NORMAL" if 0.7 <= eficiencia <= 0.9 else "REVISAR"

    return {
        "potencia_entrada": potencia_entrada,
        "potencia_mecanica": potencia_mecanica,
        "eficiencia (%)": round(eficiencia * 100, 2),
        "estado": estado
    }

reporte = diagnostico_motor(220, 8.5, 1750)
for clave, valor in reporte.items():
    print(f"{clave}: {valor}")

"""## Ejercicios

**Ejercicio 3.6: Corregir el siguiente código**
"""

def calcular_fuerza(masa, aceleracion):
    return aceleracion * masa

print(calcular_fuerza(9.8, 70))  # ¿Resultado esperado?

# Espacio para resolver el ejercicio

"""**Corrección esperada:**
El orden debe ser `calcular_fuerza(70, 9.8)`

**Ejercicio 3.7: Completa la llamada correctamente**
"""

def activar_alarma(umbral_temperatura, duracion=10):
    print(f"Alarma activada a {umbral_temperatura}°C por {duracion} segundos")

# Llamada usando parámetros nombrados
activar_alarma(_______, duracion=20)

# Espacio para resolver el ejercicio

"""#### Ejercicio 3.8: Escribe una función que devuelva el área y perímetro de un rectángulo"""

def calcular_area_perimetro(ancho, alto):

    return # Tu código aquí


# Llamada: a, p = calcular_area_perimetro(4, 3)

# Espacio para resolver el ejercicio

"""## Ejercicios Finales

###  Ejercicio de revisión:

Corrija el siguiente código para que funcione correctamente.

"""

def analizar_circuito(voltaje, corriente):
    potencia = voltaje * corriente
    resistencia = voltaje / corriente if corriente else float('inf')
    estado = "OK" if potencia < 5000 else "SOBRECARGA"
    return potencia, resistencia, estado

resultado = analizar_circuito(220, 15)
print(f"P: {p}W, R: {r:.2f}Ohm, Estado: {e}")

# Espacio para resolver el ejercicio

"""### Ejercicio de revisión:

Corrija el siguiente código para que funcione correctamente.

"""

def resumen_energia(energia_total, **componentes):
    print(f"Energía total: {energia_total}")
    for componente, energia in componentes.items():
        print(f"{componente.title()}: {energia} kWh")

    resumen_energia(500, iluminacion=120, motores=200, calefaccion=180)

# Espacio para resolver el ejercicio Indentación