# -*- coding: utf-8 -*-
"""PECIER_pandapower1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrH9CbElyjb-Q4og83XH6DOUZBtAn76E

# Introducción a Pandapower

## Ejemplos

**Ejemplos 6.5:**
"""

import pandapower as pp            # Biblioteca básica para modelar y simular redes
import pandapower.networks as pn   # Redes de prueba integradas
import pandas as pd                # ¡Pandas!
import matplotlib.pyplot as plt    # ¡Visualización!

from pandapower.networks.create_examples import example_simple

net = example_simple()

print(net)

!pip install python-igraph # Visualiza grafos y redes

!pip install igraph

"""**Ejemplo 6.6:**"""

net = pp.create_empty_network()  # Crear red vacía

bus1 = pp.create_bus(net, vn_kv=20., name="Barra Slack")
bus2 = pp.create_bus(net, vn_kv=20., name="Barra Carga")

pp.create_ext_grid(net, bus=bus1, vm_pu=1.02, name="Conexión Red")  # Slack
pp.create_load(net, bus=bus2, p_mw=5, q_mvar=2, name="Carga")
pp.create_line(net, from_bus=bus1, to_bus=bus2, length_km=10,
               std_type="NAYY 4x50 SE", name="Línea 1")

pp.runpp(net)  # Ejecuta flujo de potencia

print(net.res_bus)
print(net.res_line)

"""**Ejemplo 6.7: Redes de ejemplo**

"""

import pandapower.networks as pn
import pandapower.plotting.plotly as pf_plotly

net = pn.mv_oberrhein()  # Red de ejemplo

# Visualización
pf_plotly.simple_plotly(net)

# Lista básica de cantidad de elementos
for element in ['bus', 'line', 'trafo', 'load', 'sgen', 'gen', 'ext_grid', 'switch', 'shunt']:
    if element in net and not net[element].empty:
        print(f"{element.capitalize()}: {len(net[element])} elementos")

print(net.bus.head())

# Flujo de carga
# Porcentaje de carga de cada línea

import pandapower as pp

pp.runpp(net) # Aquí estamos ejecutando el flujo de carga
print(net.res_bus[["vm_pu", "va_degree"]])
print(net.res_line[["loading_percent"]])

"""Aspectos que se pueden explorar: ¿Hay alguna línea con carga mayor al 80%?"""

sobrecargadas=net.res_line[net.res_line["loading_percent"] > 80]
print(f"{len(sobrecargadas)}")

# ¿Cuáles son? Es decir, cuáles son los índices que cumplen.
net.res_line.index[net.res_line["loading_percent"] > 80].tolist()

"""Analizar pérdidas técnicas (por efecto Joule)"""

pp.runpp(net)
net.res_line["p_loss_mw"] = net.res_line["pl_mw"] + net.res_line["ql_mvar"] * 0  # si solo interesa potencia activa
print(net.res_line[["p_loss_mw"]])
print("Total pérdidas:", net.res_line["p_loss_mw"].sum(), "MW")

"""Agregar una carga:

"""

pp.create_load(net, bus=7, p_mw=0.5, q_mvar=0.2)
pp.runpp(net) # Vuelve a ejecutar flujo de carga para ver reflejado el cambio

print(net.res_line[["loading_percent"]])

# Existen transformadores cargados a más del 100%

trafos_sobrecargados = net.res_trafo[net.res_trafo["loading_percent"] > 100]
print(trafos_sobrecargados)

"""## Ejercicios

**Ejercicio 6.4:**

- Cambia la potencia activa de la carga a 7 MW y reactiva a 3 MVar.
"""

# Espacio para resolver el ejercicio

"""**Ejercicio 6.5:**"""

# Ejercicio:
# Con base al ejemplo 6.7: ¿Existe algún bus con voltaje por unidad superior a 1.03?

"""**Ejercicio 6.6:**"""

# 1. Programar el mostrar la cantidad de transformadores sobrecargados.
# 2. Programar el mostrar sus índices.