# -*- coding: utf-8 -*-
"""PECIER_modulo7_parte3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyEiqh5dY28I8SI1uzvCYkzSE4z_NMZT

# Día 7 Parte 3: Aplicaciones de LLMs en el Sector Eléctrico

## Ejemplos

**Ejemplo 7.6:**
"""

datos = pd.DataFrame({
    "Parámetro": ["Voltaje L1", "Voltaje L2", "Voltaje L3", "Temp. Transformador"],
    "Valor": [132.4, 131.8, 85.2, 78],
    "Límite": ["130±5%", "130±5%", "130±5%", "75 máx"]
})

asistente = AsistenteSCADA(client)
print(asistente.analizar(datos))

"""**Ejemplo 7.7:**"""

datos = {
    "hora": ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"],
    "valor": [132.1, 131.5, 150.2, 149.8, 133.2, 132.8],
    "limite": [130, 130, 130, 130, 130, 130]
}

df_resultado, analisis = detectar_anomalias(datos)
print(df_resultado)
print("\nAnálisis del modelo:")
print(analisis)

"""**Ejemplo 7.8:**"""

base = {
    "protección diferencial": "Artículo 7.3 del reglamento establece ajustes de sensibilidad mínima de 0.3 A.",
    "factor de potencia": "La normativa indica mínimo 0.95 para conexión en media tensión."
}

asistente = AsistenteTecnico(base)
print(asistente.responder("¿Qué factor de potencia mínimo se requiere en media tensión?"))

"""## Ejercicios

**Ejercicio 7.5:**

Agrega un nuevo parámetro llamado `"Frecuencia"` con valor `59.1` Hz y límite `"60±1%"`. ¿Cómo cambia el análisis?
"""

# Espacio para resolver el ejercicio

"""**Ejercicio 7.6:**

Cambia la capacidad a `"250 MVA"` y agrega un nuevo incidente: `"Alarma por bajo voltaje 22/11"`. ¿Cómo se actualiza el informe?

"""

# Espacio para resolver el ejercicio

"""**Ejercicio 7.7:**

Modifica la función para incluir un encabezado con fecha y nombre del operador.

"""

# Espacio para resolver el ejercicio

"""**Ejercicio 7.8:**

Simula datos de frecuencia horaria (`valor` en Hz, `limite = 60`) y verifica si se detectan desviaciones.
"""

# Espacio para resolver el ejercicio

"""**Ejercicio 7.9:**

Agrega una entrada sobre “reconexión automática” y consulta si es recomendable para sistemas rurales.

"""

# Espacio para resolver el ejercicio