# -*- coding: utf-8 -*-
"""PECIER_dia2_parte3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cXxoYGEXWD-l351AEaOv0GNMfO71qZJY

## **Día 2 Sección 3: Ejercicios Prácticos**

## Ejemplos

**Ejemplo 2.15: Procesamiento de mediciones diarias**
"""

# Ejemplo: Procesamiento de mediciones diarias
mediciones = [
    [218, 215, 220],  # Lunes
    [222, 219, 225],  # Martes
    [210, 212, 208]   # Miércoles
]

# Calcular promedio por día
promedios = [sum(dia)/len(dia) for dia in mediciones]
print("Promedios diarios:", promedios)

"""**Salida Esperada:**

Promedios diarios: [217.66666666666666, 222.0, 210.0]


**Esto nos muestra los promedios de voltaje para cada día de la semana.**

### **Actualización de Stock**

El código a continuación simula un proceso de **actualización de inventarios** al registrar un movimiento de stock (por ejemplo, la venta de 30 unidades de baterías).
"""

# Base de datos de componentes
componentes = {
    "Baterías": {
        "Tipo": "Li-ion",
        "Capacidad": "100Ah",
        "Stock": 35
    },
    "Paneles": {
        "Tipo": "Monocristalino",
        "Watt": 350,
        "Stock": 20
    }
}

# Lista para registrar los movimientos de stock
movimientos = []

# Componente al que le vamos a hacer la actualización: "Baterías"
nombre = "Baterías"
cantidad = 30

# Verificar si hay suficiente stock antes de restar
if componentes[nombre]["Stock"] >= cantidad:
    # Actualizar el stock
    componentes[nombre]["Stock"] -= cantidad
    # Registrar el movimiento
    movimientos.append(f"Restado {cantidad} unidades de {nombre}. Nuevo stock: {componentes[nombre]['Stock']}")

    # Verificar si el stock es bajo
    if componentes[nombre]["Stock"] < 5:
        print(f"¡Alerta! Stock bajo de {nombre}")
else:
    print(f"Error: No hay suficiente stock de {nombre}. Stock actual: {componentes[nombre]['Stock']}")

# Mostrar el historial de movimientos
print("\nHistorial de movimientos:")
for movimiento in movimientos:
    print(movimiento)

"""#### **Importante**:

- **Actualización de Stock**: Verificamos si el stock es suficiente antes de realizar la venta (restar las unidades). Si el stock baja de 5, se imprime una alerta.
- **Historial de movimientos**: Cada vez que se actualiza el stock, se registra un movimiento para llevar un historial completo de las transacciones.

### **Ejemplos adicionales avanzados**

**Ejemplo 2.18 Análisis de Calidad de Energía**

En sistemas eléctricos, uno de los indicadores clave de calidad de energía es la **Distorsión Armónica Total (THD)**. Un valor THD elevado puede indicar problemas en la calidad de la energía suministrada.
"""

# Datos de THD (Total Harmonic Distortion) por fase
thd = {
    "Fase A": [2.1, 2.3, 2.0, 5.1, 1.9],  # Último valor sospechoso
    "Fase B": [2.0, 2.1, 2.2, 2.0, 2.3],
    "Fase C": [2.2, 2.4, 7.0, 2.1, 2.2]   # Valor crítico
}

# Identificar valores >5%
for fase, valores in thd.items():
    anomalias = [v for v in valores if v > 5]
    if anomalias:
        print(f"¡Alerta en {fase}! Valores críticos: {anomalias}")

"""**Explicación**:

- Cada fase tiene un conjunto de mediciones de THD. Si algún valor supera el umbral crítico de 5%, se emite una alerta.
- Usamos una comprensión de lista ([v for v in valores if v > 5]) para identificar los valores que superan el umbral.

#### **2. Sistema de Facturación**

El siguiente código muestra cómo calcular la **factura** de un cliente eléctrico dependiendo de su tipo (residencial o comercial) y su consumo.
"""

# Definición de tarifas por tipo de cliente
tarifas = {
    "Residencial": {"cargo_fijo": 5.00, "precio_kWh": 0.15},
    "Comercial": {"cargo_fijo": 10.00, "precio_kWh": 0.12}
}

# Datos del cliente
cliente_ejemplo = {"nombre": "Juan Pérez", "tipo": "Residencial"}

# Datos de consumo en kWh
consumo_kWh = 350

# Determinar el tipo de cliente y calcular la factura
tipo = cliente_ejemplo["tipo"]
subtotal = consumo_kWh * tarifas[tipo]["precio_kWh"]
total = subtotal + tarifas[tipo]["cargo_fijo"]

# Generar y mostrar la factura
factura = {
    "Cliente": cliente_ejemplo["nombre"],
    "Tipo": tipo,
    "Total": f"${total:.2f}"
}

# Imprimir la factura
print(factura)

"""### **Ejemplo Final**
**Sistema de Gestión de Subestaciones**

Este ejemplo final simula el **gestor de carga** de una subestación eléctrica, permitiendo monitorear la capacidad de la subestación en términos de la carga total (medida en MVA) y verificar si se excede.

"""

# Datos iniciales de la subestación
nombre_subestacion = "Norte"
capacidad_MVA = 50
transformadores = []

# Agregar transformador 1
nombre_transformador_1 = "T1"
MVA_transformador_1 =

 30
transformadores.append({"nombre": nombre_transformador_1, "MVA": MVA_transformador_1})

# Verificar si la capacidad se ha excedido
if sum(t["MVA"] for t in transformadores) > capacidad_MVA:
    print(f"¡Advertencia! Capacidad excedida en {nombre_subestacion}")

# Agregar transformador 2
nombre_transformador_2 = "T2"
MVA_transformador_2 = 25
transformadores.append({"nombre": nombre_transformador_2, "MVA": MVA_transformador_2})

# Verificar si la capacidad se ha excedido
if sum(t["MVA"] for t in transformadores) > capacidad_MVA:
    print(f"¡Advertencia! Capacidad excedida en {nombre_subestacion}")

# Generar reporte de la subestación
carga_total = sum(t["MVA"] for t in transformadores)
reporte = {
    "Nombre": nombre_subestacion,
    "Transformadores": len(transformadores),
    "Carga Total": f"{carga_total}/{capacidad_MVA} MVA"
}

# Imprimir el reporte
print(reporte

"""Explicación:

Se lleva un registro de los transformadores y su carga (MVA) dentro de la subestación.
Si la carga total supera la capacidad máxima, se emite una advertencia.

## Ejercicios

#### **Ejercicio 2.17:**
**Desviación estándar para cada día usando `statistics.stdev`.**

Determine el error, y corríjalo en el siguiente código:
"""

import statistics

# Ejemplo: Procesamiento de mediciones diarias
mediciones = [
    [218, 215, 220],  # Lunes
    [222, 219, 225],  # Martes
    [210, 212, 208]   # Miércoles
]

# Calcular desviación estándar por día
desviaciones = [statistics.stdev(dia) for i in mediciones]
print("Desviaciones estándar diarias:", desviaciones)

# Espacio para resolver el ejercicio:
