# -*- coding: utf-8 -*-
"""PECIER_Modulo4_parte1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zHGHpmh01oWuk_-TfOwgged_xAiD5ID

# Día 4 Parte 1: Uso de Bibliotecas Numéricas - NumPy

## Ejemplos

**Ejemplo 4.1:** Definición de un array
"""

import numpy as np

tensiones = np.array([220.5, 221.3, 219.8, 220.2, 222.1])

"""**Ejemplo 4.2:** Array multidimensional"""

import numpy as np

sistema_trifasico = np.array([
    [220.1, 219.8, 220.5],  # Fase R
    [219.9, 220.2, 220.0],  # Fase S
    [220.3, 220.1, 219.7]   # Fase T
])

"""**Ejemplo 4.3:** Promedios en arrays"""

import numpy as np
# Promedio de tensión por fase
promedios_por_fase = np.mean(sistema_trifasico, axis=1)

# Promedio de tensión por instante de tiempo
promedios_por_instante = np.mean(sistema_trifasico, axis=0)

"""**Ejemplo 4.4:** Creación de arrays con rango de valores"""

import numpy as np
# Rango de frecuencias de 50Hz a 60Hz con paso de 0.5Hz
frecuencias = np.arange(50, 60.5, 0.5)

"""**Ejemplo 4.5:** Creación de arrays con valores equidistantes"""

import numpy as np
# 10 valores espaciados linealmente entre 0 y 10V
tensiones_lin = np.linspace(0, 10, 10)

"""**Ejemplo 4.6:** Matriz identidad

"""

import numpy as np
# Matriz identidad 3x3 (como en matrices de impedancia)
matriz_identidad = np.eye(3)

"""**Ejemplo 4.7:** Operaciones matemáticas"""

import numpy as np

# Tensiones medidas en volts
tensiones = np.array([220.5, 221.3, 219.8, 220.2, 222.1])

# Corrientes medidas en amperes
corrientes = np.array([10.2, 9.8, 10.5, 11.1, 10.9])

# Potencias instantáneas calculadas como P = V * I
potencias = tensiones * corrientes

"""## Ejercicios

***Ejercicio 4.1:***

¿Es posible realizar el producto del Ejemplo 4.7 sin Numpy, usando simplemente listas?
"""

# Espacio para resolver el ejercicio

"""**Ejercicio 4.2:** Determinar si existen errores cuando no coinciden las dimensiones de dos arrays que se multiplican. Puede retomar del Ejempo 4.7


"""

# Espacio para resolver el ejercicio

"""**Ejercicio 4.3:** Si con tensiones.shape establecemos el tamaño de un array, cambiar el código anterior para incluir una verificación de que las dimensiones de tensiones y corrientes coinciden antes de obtener las potencias.


"""

# Espacio para resolver el ejercicio
# Ayuda:

# Verificación previa
if tensiones.shape == corrientes.shape:
    potencias = tensiones * corrientes
    print("Potencias calculadas:", potencias)
else:
    print("Error: Las dimensiones de tensiones y corrientes no coinciden.")
    print("Tensiones:", tensiones.shape)
    print("Corrientes:", corrientes.shape)

"""**Ejercicio 4.4:** Utilizar una función para cortar los arrays para que coincidan en tamaño (usar con precaución)"""

#Espacio para resolver el ejercicio:
#Ayuda:
min_len = min(len(tensiones), len(corrientes))
potencias = tensiones[:min_len] * corrientes[:min_len]

"""# **Ejemplos adicionales**

**Análisis de Consumo Eléctrico**

Analizar un array de consumo horario de energía de una subestación, calculando el consumo promedio diario, la hora pico de consumo y la variación porcentual respecto al día anterior.
"""

import numpy as np

# Datos de consumo horario en kWh (simulados)
consumo_horario = np.array([
    100, 120, 110, 130, 125, 140, 150, 160, 170, 180, 200, 210,  # Día 1
    190, 180, 160, 150, 140, 130, 120, 110, 100, 95, 90, 85,
    100, 120, 110, 130, 125, 140, 150, 160, 170, 180, 200, 210,  # Día 2
    190, 180, 160, 150, 140, 130, 120, 110, 100, 95, 90, 85,
    100, 120, 110, 130, 125, 140, 150, 160, 170, 180, 200, 210,  # Día 3
    190, 180, 160, 150, 140, 130, 120, 110, 100, 95, 90, 85,
    100, 120, 110, 130, 125, 140, 150, 160, 170, 180, 200, 210,  # Día 4
    190, 180, 160, 150, 140, 130, 120, 110, 100, 95, 90, 85,
    100, 120, 110, 130, 125, 140, 150, 160, 170, 180, 200, 210,  # Día 5
    190, 180, 160, 150, 140, 130, 120, 110, 100, 95, 90, 85,
    100, 120, 110, 130, 125, 140, 150, 160, 170, 180, 200, 210,  # Día 6
    190, 180, 160, 150, 140, 130, 120, 110, 100, 95, 90, 85,
    100, 120, 110, 130, 125, 140, 150, 160, 170, 180, 200, 210   # Día 7
])


# 1. Consumo promedio diario
consumo_diario = consumo_horario.reshape(-1, 24)  # Reshape a 7 días
consumo_promedio_diario = np.mean(consumo_diario, axis=1)
print(f"Consumo promedio diario: {consumo_promedio_diario}")

# 2. Hora pico de consumo (máxima demanda en cualquier hora)
hora_pico = np.argmax(consumo_horario) % 24
print(f"Hora pico de consumo: {hora_pico}:00 h")

# 3. Variación porcentual respecto al día anterior
variacion_porcentual = np.diff(consumo_promedio_diario) / consumo_promedio_diario[:-1] * 100
print(f"Variación porcentual diaria: {variacion_porcentual}")

"""Nota: reshape(-1, 24) significa que: 24 es el número de columnas, que corresponde a las 24 horas de cada día. -1 le dice a NumPy que calcule automáticamente el número de filas necesarias para que el array tenga 168 elementos.

**Preguntas:**

1. ¿Qué forma tiene el array luego del código consumo_diario = consumo_horario.reshape(-1, 24) ?
"""

# Espacio para responder

"""2. ¿Qué hace la siguiente línea del código?

hora_pico = np.argmax(consumo_horario) % 24
"""

# Espacio para responder

"""---

**Balance de Fases:** Calcular el desbalance de corriente entre las tres fases, la fase con mayor corriente y la corriente promedio.
"""

# Datos de corrientes de las fases en amperios (simulados)
corrientes_fases = np.array([
    [10.0, 12.0, 11.5],  # Fase R
    [10.5, 11.0, 12.0],  # Fase S
    [11.0, 10.0, 10.5],  # Fase T
])

# 1. Desbalance de corriente (%)
media_corrientes = np.mean(corrientes_fases, axis=1)
desbalance = np.max(media_corrientes) - np.min(media_corrientes)
desbalance_porcentaje = (desbalance / np.mean(media_corrientes)) * 100
print(f"Desbalance de corriente (%): {desbalance_porcentaje:.2f}%")

# 2. Fase con mayor corriente
fase_max_corriente = np.argmax(media_corrientes)
print(f"Fase con mayor corriente: {'RST'[fase_max_corriente]}")

# 3. Corriente promedio
corriente_promedio = np.mean(corrientes_fases)
print(f"Corriente promedio: {corriente_promedio:.2f} A")